test_readGrammar:	readGrammar.c for_readGrammar.c driver_test_for_readGrammar.c
	gcc -g readGrammar.c for_readGrammar.c driver_test_for_readGrammar.c -o test_rdgm
bobj_test_readGrammar: readGrammar.c for_readGrammar.c driver_test_for_readGrammar.c
	gcc -c  -g readGrammar.c for_readGrammar.c driver_test_for_readGrammar.c
	
	
