test_readGrammar:	readGrammar.o for_readGrammar.o driver_test_for_readGrammar.o
	gcc readGrammar.o for_readGrammar.o driver_test_for_readGrammar.o -o test_rdgm
bobj_test_readGrammar: readGrammar.c for_readGrammar.c driver_test_for_readGrammar.c
	gcc -c readGrammar.c for_readGrammar.c driver_test_for_readGrammar.c
	
	
