compile_td_tokeniseSourceCode: linked_list.c is_ID.c identify_token.c is_keyword.c is_constant.c tokeniseSourceCode.c td_tokeniseSourceCode.c 
	gcc -g is_ID.c is_keyword.c is_constant.c identify_token.c tokeniseSourceCode.c td_tokeniseSourceCode.c -o td_tokeniseSourceCode
